version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    command: python filmanija.py

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend